version: '3.9' # Specify the Compose file format version

services:
  laravel-docker:
    container_name: laravel_docker_news
    build: .
    volumes:
      - ./dockerize_lara_app:/var/www/html
    ports:
      - 8090:80
  
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: dockerize_db         
      MYSQL_USER: user             
      MYSQL_PASSWORD: root      
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_news
    ports:
      - 9001:80
    environment:
      PMA_HOST: mysql_db
      PMA_USER: user
      PMA_PASSWORD: root
